server:
  port: 8082

spring:
  application:
    name: jareer-ai

  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY: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}
      chat:
        options:
          model: llama-3.1-8b-instant
logging:
  level:
    org.springframework.ai: INFO
